export const cards = [
  {
    name: "Bombas para piscina",
    description: "Toda la línea de autocebantes Vulcano al mejor precio.",
    link: "/piscinas/bombas-autocebantes",
    url: "/assets/category_1-50.jpg",
  },
  {
    name: "Filtros para piscina",
    description: "Las mejores ofertas en filtros Vulcano.",
    link: "/piscinas/filtros",
    url: "/assets/category_2-50.jpg",
  },
];

export const env = {
  MERCADOPAGO_TOKEN: process.env.MERCADOPAGO_TOKEN,
  MERCADOPAGO_URL: process.env.MERCADOPAGO_URL,
  MONGODB_URI: process.env.MONGODB_URI,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
};

export const features = [
  {
    name: "Accesorios de Instalación",
    url: "accesorios-de-instalacion",
    category: "Piscinas",
  },
  {
    name: "Automatización",
    url: "automatizacion",
    category: "Piscinas",
  },
  {
    name: "Bombas Autocebantes",
    url: "bombas-autocebantes",
    category: "Piscinas",
  },
  {
    name: "Climatización",
    url: "climatizacion",
    category: "Piscinas",
  },
  {
    name: "Diseño y Confort",
    url: "diseno-y-confort",
    category: "Piscinas",
  },
  {
    name: "Filtros",
    url: "filtros",
    category: "Piscinas",
  },
  {
    name: "Iluminación",
    url: "iluminacion",
    category: "Piscinas",
  },
  {
    name: "Limpieza",
    url: "limpieza",
    category: "Piscinas",
  },
];

export const paymentMethods = [
  {
    name: "Tarjeta de crédito",
    icon: <i className="fi fi-rr-bank icon"></i>,
  },
  {
    name: "Tarjeta de débito",
    icon: <i className="fi fi-rr-credit-card icon"></i>,
  },
  {
    name: "Cuotas sin tarjeta",
    icon: <i className="fi fi-rr-hand-holding-usd icon"></i>,
  },
  {
    name: "Efectivo",
    icon: <i className="fi fi-rr-money-bill-wave icon"></i>,
  },
];

export const quantities = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export const region = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

// const checkout_mercadopagoResponse = {
//   body: {
//     additional_info: "",
//     auto_return: "",
//     back_urls: {
//       failure: "https://main.d3230oyu2t880h.amplifyapp.com/bag",
//       pending: "https://main.d3230oyu2t880h.amplifyapp.com/profile",
//       success: "https://main.d3230oyu2t880h.amplifyapp.com/profile",
//     },
//     binary_mode: false,
//     client_id: "5189779300400266",
//     collector_id: 103268085,
//     coupon_code: null,
//     coupon_labels: null,
//     date_created: "2023-08-30T10:18:40.331-04:00",
//     date_of_expiration: null,
//     expiration_date_from: null,
//     expiration_date_to: null,
//     expires: false,
//     external_reference: "",
//     id: "103268085-ff2bf95a-0490-4a12-ac8d-34e2fa96bce2",
//     init_point:
//       "https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=103268085-ff2bf95a-0490-4a12-ac8d-34e2fa96bce2",
//     internal_metadata: null,
//     items: [[Object]],
//     marketplace: "MP-MKT-5189779300400266",
//     marketplace_fee: 0,
//     metadata: {},
//     notification_url: "https://main.d3230oyu2t880h.amplifyapp.com/api/payment",
//     operation_type: "regular_payment",
//     payer: {
//       phone: [Object],
//       address: [Object],
//       email: "",
//       identification: [Object],
//       name: "",
//       surname: "",
//       date_created: null,
//       last_purchase: null,
//     },
//     payment_methods: {
//       default_card_id: null,
//       default_payment_method_id: null,
//       excluded_payment_methods: [Array],
//       excluded_payment_types: [Array],
//       installments: null,
//       default_installments: null,
//     },
//     processing_modes: null,
//     product_id: null,
//     redirect_urls: { failure: "", pending: "", success: "" },
//     sandbox_init_point:
//       "https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=103268085-ff2bf95a-0490-4a12-ac8d-34e2fa96bce2",

//     site_id: "MLA",
//     shipments: { default_shipping_method: null, receiver_address: [Object] },
//     total_amount: null,
//     last_updated: null,
//   },
//   status: 201,
//   idempotency: undefined,
//   pagination: undefined,
// };

// const webhook_request = {
//   action: "payment.created",
//   api_version: "v1",
//   data: { id: "1317514189" },
//   date_created: "2023-08-30T12:42:24Z",
//   id: 107293030343,
//   live_mode: false,
//   type: "payment",
//   user_id: "103268085",
// };

// const webhook_mercadopagoResponse = {
//   body: {
//     accounts_info: null,
//     acquirer_reconciliation: [],
//     additional_info: {
//       authentication_code: null,
//       available_balance: null,
//       ip_address: "181.228.206.226",
//       items: [Array],
//       nsu_processadora: null,
//     },
//     authorization_code: null,
//     binary_mode: false,
//     brand_id: null,
//     build_version: "3.14.0-rc-4",
//     call_for_authorize_id: null,
//     captured: true,
//     card: {
//       cardholder: [Object],
//       date_created: "2023-08-30T10:19:34.000-04:00",
//       date_last_updated: "2023-08-30T10:19:34.000-04:00",
//       expiration_month: 11,
//       expiration_year: 2025,
//       first_six_digits: "450995",
//       id: null,
//       last_four_digits: "3704",
//     },
//     charges_details: [],
//     collector_id: 103268085,
//     corporation_id: null,
//     counter_currency: null,
//     coupon_amount: 0,
//     currency_id: "ARS",
//     date_approved: "2023-08-30T10:19:34.892-04:00",
//     date_created: "2023-08-30T10:19:34.734-04:00",
//     date_last_updated: "2023-08-30T10:19:34.892-04:00",
//     date_of_expiration: null,
//     deduction_schema: null,
//     description: "Bomba BAP para piscina",
//     differential_pricing_id: null,
//     external_reference: null,
//     fee_details: [[Object]],
//     financing_group: null,
//     id: 1317515789,
//     installments: 1,
//     integrator_id: null,
//     issuer_id: "310",
//     live_mode: false,
//     marketplace_owner: 103268085,
//     merchant_account_id: null,
//     merchant_number: null,
//     metadata: {},
//     money_release_date: "2023-09-17T10:19:34.892-04:00",
//     money_release_schema: null,
//     money_release_status: null,
//     notification_url: "https://main.d3230oyu2t880h.amplifyapp.com/api/payment",
//     operation_type: "regular_payment",
//     order: { id: "11427418621", type: "mercadopago" },
//     payer: {
//       first_name: null,
//       last_name: null,
//       email: "test_user_80507629@testuser.com",
//       identification: [Object],
//       phone: [Object],
//       type: null,
//       entity_type: null,
//       id: "192180541",
//     },
//     payment_method: { id: "visa", issuer_id: "310", type: "credit_card" },
//     payment_method_id: "visa",
//     payment_type_id: "credit_card",
//     platform_id: null,
//     point_of_interaction: {
//       business_info: [Object],
//       transaction_data: [Object],
//       type: "CHECKOUT",
//     },
//     pos_id: null,
//     processing_mode: "aggregator",
//     refunds: [],
//     shipping_amount: 0,
//     sponsor_id: null,
//     statement_descriptor: "SRS",
//     status: "approved",
//     status_detail: "accredited",
//     store_id: null,
//     tags: null,
//     taxes_amount: 0,
//     transaction_amount: 50,
//     transaction_amount_refunded: 0,
//     transaction_details: {
//       acquirer_reference: null,
//       external_resource_url: null,
//       financial_institution: null,
//       installment_amount: 50,
//       net_received_amount: 47.95,
//       overpaid_amount: 0,
//       payable_deferral_period: null,
//       payment_method_reference_id: null,
//       total_paid_amount: 50,
//     },
//   },
// };
