import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Footer, Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nike store",
  description: "Generated by Proficient.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col items-center justify-between text-primary-black ${inter.className}`}
      >
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
